name: Build on Push to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore TextToSpeech.sln

    - name: Build the solution
      run: msbuild TextToSpeech/TextToSpeech.csproj /p:Configuration=Release
