name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore TextToSpeech.sln

    # Step 1: Build the WinForms project
    - name: Build WinForms Project
      run: msbuild TextToSpeech/TextToSpeech.csproj /p:Configuration=Release

      - name: Copy EULA file to output directory
      run: |
        mkdir "$(Build.BinariesDirectory)\TextToSpeechInstaller"
        copy "TextToSpeechInstaller\Eula-en.rtf" "$(Build.BinariesDirectory)\TextToSpeechInstaller\Eula-en.rtf"

    # Step 2: Build the Wix Installer project
    - name: Build Wix Installer Project
      run: msbuild TextToSpeechInstaller/TextToSpeechInstaller.wixproj /p:Configuration=Release
